trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

  Major: '0'
  Minor: '1'
  Patch: '0'

name: $(Major).$(Minor).$(Patch)

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: NuGetCommand@2
  displayName: 'NuGet Pack for Core'
  inputs:
    command: pack
    packagesToPack: '**/Mockable.Core.csproj'
    packDestination: '$(Build.ArtifactStagingDirectory)'
    versioningScheme: byBuildNumber

- task: NuGetCommand@2
  displayName: 'NuGet Push for Core'
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: nuget.org
